apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--backend-service
spec:
  ports:
    - name: "http"
      port: 8000
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}--backend

