apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--client-service
spec:
  ports:
    - name: "http"
      port: 8082
      targetPort: 80
  selector:
    app: {{ .Release.Name }}--client

