apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--runjail
spec:
  replicas: {{ .Values.runjail.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}--runjail
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}--runjail
        app.kubernetes.io/name: {{ .Release.Name }}--runjail
    spec:
      containers:
        - image: {{ .Values.runjail.image.name }}:{{ .Values.runjail.image.version }}
          name: runjail
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: 1556
          readinessProbe:
            tcpSocket:
              port: 1556
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 1556
            initialDelaySeconds: 15
            periodSeconds: 20
