apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}--backend-ingress
spec:
  rules:
    - host: {{ .Values.backend.hostName }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Release.Name }}--backend-service
                port:
                  name: http
