apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--backend
spec:
  replicas: {{ .Values.backend.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}--backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}--backend
        app.kubernetes.io/name: {{ .Release.Name }}--backend
    spec:
      initContainers:
        - image: {{ .Values.backend.image.name }}:{{ .Values.backend.image.version }}
          name: backend-init
          imagePullPolicy: {{ .Values.pullPolicy }}
          command:
            - /bin/bash
            - -c
          args:
            - poetry run python manage.py migrate;
          volumeMounts:
            - mountPath: /code/sqlite
              name: sqlite
            {{ if .Values.client.mountDist }}
            - mountPath: /code/practicode_backend
              name: src
            {{ end }}
      containers:
        - image: {{ .Values.backend.image.name }}:{{ .Values.backend.image.version }}
          name: backend
          imagePullPolicy: {{ .Values.pullPolicy }}
          command: [ "/bin/bash", "-c" ]
          args:
            - poetry run python manage.py runserver 0.0.0.0:8000
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /code/sqlite
              name: sqlite
            {{ if .Values.client.mountDist }}
            - mountPath: /code/practicode_backend
              name: src
            {{ end }}
          env:
            - name: PRACTICODE_BACKEND_ENDPOINT
              value: {{ .Values.backend.hostName }}
            - name: PRACTICODE_CLIENT_HOST
              value: http://{{ .Values.client.hostName }}
            - name: PRACTICODE_RUNJAIL_WEBSOCKET
              value: ws://{{ .Values.runjail.hostName }}/run
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: sqlite
          emptyDir: {}
        {{ if .Values.backend.mountSrc }}
        - name: src
          hostPath:
            path: {{ .Values.backend.mountSrc }}
        {{ end }}
